title: The Mighty Hand of God
author: Lopin hoppers
email: support@bragaboutgod.me
description: > # this means to ignore newlines until "baseurl:"
  God is awsome and he always shows up for his kids, 
  he never leaves us stranded or in trouble,
  because he loves us dearly, tho the earth 
  may fad away but the love of god never fades its new every morning, 
  grows stronger and stonger as we contine to ask for more grace.

# social links
twitter_username: bragaboutgod # DO NOT include the @ character, or else the build will fail!
github_username:  bragaboutgod # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
